///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyWebVIPTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyWebVIPTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("01c5e881-187a-4fa0-90ca-eb7438950196")]
    public partial class MyWebVIPTestRepository : RepoGenBaseFolder
    {
        static MyWebVIPTestRepository instance = new MyWebVIPTestRepository();
        MyWebVIPTestRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;

        /// <summary>
        /// Gets the singleton class instance representing the MyWebVIPTestRepository element repository.
        /// </summary>
        [RepositoryFolder("01c5e881-187a-4fa0-90ca-eb7438950196")]
        public static MyWebVIPTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyWebVIPTestRepository() 
            : base("MyWebVIPTestRepository", "/", null, 0, false, "01c5e881-187a-4fa0-90ca-eb7438950196", ".\\RepositoryImages\\MyWebVIPTestRepository01c5e881.rximgres")
        {
            _ranorexvipdatabasetestwebapplicatio = new MyWebVIPTestRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("01c5e881-187a-4fa0-90ca-eb7438950196")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("71ed5ed4-cabc-4650-8ac0-10e5d81f814c")]
        public virtual MyWebVIPTestRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyWebVIPTestRepositoryFolders
    {
        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("71ed5ed4-cabc-4650-8ac0-10e5d81f814c")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            MyWebVIPTestRepositoryFolders.Category_RootedFolderFolder _category_rootedfolder;
            MyWebVIPTestRepositoryFolders.RadioButtons_RootedFolderFolder _radiobuttons_rootedfolder;
            MyWebVIPTestRepositoryFolders.InputFieldsFolder _inputfields;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "71ed5ed4-cabc-4650-8ac0-10e5d81f814c", "")
            {
                _category_rootedfolder = new MyWebVIPTestRepositoryFolders.Category_RootedFolderFolder(this);
                _radiobuttons_rootedfolder = new MyWebVIPTestRepositoryFolders.RadioButtons_RootedFolderFolder(this);
                _inputfields = new MyWebVIPTestRepositoryFolders.InputFieldsFolder(this);
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", 30000, null, "161832a9-d4f0-4a46-b6c2-d4a9275c9054");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", 30000, null, "fdd88167-94cf-4273-9873-0bb034b7af78");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("71ed5ed4-cabc-4650-8ac0-10e5d81f814c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("71ed5ed4-cabc-4650-8ac0-10e5d81f814c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("161832a9-d4f0-4a46-b6c2-d4a9275c9054")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("161832a9-d4f0-4a46-b6c2-d4a9275c9054")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("fdd88167-94cf-4273-9873-0bb034b7af78")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("fdd88167-94cf-4273-9873-0bb034b7af78")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Category_RootedFolder folder.
            /// </summary>
            [RepositoryFolder("7287bfdb-bc40-48c4-82e5-42f03090dbe4")]
            public virtual MyWebVIPTestRepositoryFolders.Category_RootedFolderFolder Category_RootedFolder
            {
                get { return _category_rootedfolder; }
            }

            /// <summary>
            /// The RadioButtons_RootedFolder folder.
            /// </summary>
            [RepositoryFolder("cd529c39-7341-4946-b20e-ac9db4de689a")]
            public virtual MyWebVIPTestRepositoryFolders.RadioButtons_RootedFolderFolder RadioButtons_RootedFolder
            {
                get { return _radiobuttons_rootedfolder; }
            }

            /// <summary>
            /// The InputFields folder.
            /// </summary>
            [RepositoryFolder("732e234d-eb57-4049-84d3-53cd124fb000")]
            public virtual MyWebVIPTestRepositoryFolders.InputFieldsFolder InputFields
            {
                get { return _inputfields; }
            }
        }

        /// <summary>
        /// The Category_RootedFolderFolder folder.
        /// </summary>
        [RepositoryFolder("7287bfdb-bc40-48c4-82e5-42f03090dbe4")]
        public partial class Category_RootedFolderFolder : RepoGenBaseFolder
        {
            RepoItemInfo _otherInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _movieInfo;

            /// <summary>
            /// Creates a new Category_RootedFolder  folder.
            /// </summary>
            public Category_RootedFolderFolder(RepoGenBaseFolder parentFolder) :
                    base("Category_RootedFolder", ".//select[#'Category']", parentFolder, 30000, null, false, "7287bfdb-bc40-48c4-82e5-42f03090dbe4", "")
            {
                _otherInfo = new RepoItemInfo(this, "Other", "option[@value='Other']", 30000, null, "45a17821-c855-41a2-ac94-d053f5a73624");
                _musicInfo = new RepoItemInfo(this, "Music", "option[@value='Music']", 30000, null, "53b64186-1e20-4e1b-808b-ea5029bf72ed");
                _movieInfo = new RepoItemInfo(this, "Movie", "option[@value='Movie']", 30000, null, "fed00b08-048f-4c66-82fb-79ca56ff87b5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7287bfdb-bc40-48c4-82e5-42f03090dbe4")]
            public virtual Ranorex.SelectTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7287bfdb-bc40-48c4-82e5-42f03090dbe4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Other item.
            /// </summary>
            [RepositoryItem("45a17821-c855-41a2-ac94-d053f5a73624")]
            public virtual Ranorex.OptionTag Other
            {
                get
                {
                    return _otherInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Other item info.
            /// </summary>
            [RepositoryItemInfo("45a17821-c855-41a2-ac94-d053f5a73624")]
            public virtual RepoItemInfo OtherInfo
            {
                get
                {
                    return _otherInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("53b64186-1e20-4e1b-808b-ea5029bf72ed")]
            public virtual Ranorex.OptionTag Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("53b64186-1e20-4e1b-808b-ea5029bf72ed")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("fed00b08-048f-4c66-82fb-79ca56ff87b5")]
            public virtual Ranorex.OptionTag Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("fed00b08-048f-4c66-82fb-79ca56ff87b5")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }
        }

        /// <summary>
        /// The RadioButtons_RootedFolderFolder folder.
        /// </summary>
        [RepositoryFolder("cd529c39-7341-4946-b20e-ac9db4de689a")]
        public partial class RadioButtons_RootedFolderFolder : RepoGenBaseFolder
        {
            RepoItemInfo _maleInfo;
            RepoItemInfo _femaleInfo;

            /// <summary>
            /// Creates a new RadioButtons_RootedFolder  folder.
            /// </summary>
            public RadioButtons_RootedFolderFolder(RepoGenBaseFolder parentFolder) :
                    base("RadioButtons_RootedFolder", ".//td[#'gender']/table", parentFolder, 30000, null, false, "cd529c39-7341-4946-b20e-ac9db4de689a", "")
            {
                _maleInfo = new RepoItemInfo(this, "Male", ".//input[@name='Gender' and @type='radio' and @value='male']", 30000, null, "da9c1a4a-f858-4475-9479-b2158ed7d558");
                _femaleInfo = new RepoItemInfo(this, "Female", ".//input[@id='Gender']", 30000, null, "1e460f15-4428-4257-8199-892cb5e23343");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd529c39-7341-4946-b20e-ac9db4de689a")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd529c39-7341-4946-b20e-ac9db4de689a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Male item.
            /// </summary>
            [RepositoryItem("da9c1a4a-f858-4475-9479-b2158ed7d558")]
            public virtual Ranorex.InputTag Male
            {
                get
                {
                    return _maleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Male item info.
            /// </summary>
            [RepositoryItemInfo("da9c1a4a-f858-4475-9479-b2158ed7d558")]
            public virtual RepoItemInfo MaleInfo
            {
                get
                {
                    return _maleInfo;
                }
            }

            /// <summary>
            /// The Female item.
            /// </summary>
            [RepositoryItem("1e460f15-4428-4257-8199-892cb5e23343")]
            public virtual Ranorex.InputTag Female
            {
                get
                {
                    return _femaleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Female item info.
            /// </summary>
            [RepositoryItemInfo("1e460f15-4428-4257-8199-892cb5e23343")]
            public virtual RepoItemInfo FemaleInfo
            {
                get
                {
                    return _femaleInfo;
                }
            }
        }

        /// <summary>
        /// The InputFieldsFolder folder.
        /// </summary>
        [RepositoryFolder("732e234d-eb57-4049-84d3-53cd124fb000")]
        public partial class InputFieldsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;

            /// <summary>
            /// Creates a new InputFields  folder.
            /// </summary>
            public InputFieldsFolder(RepoGenBaseFolder parentFolder) :
                    base("InputFields", "", parentFolder, 0, null, false, "732e234d-eb57-4049-84d3-53cd124fb000", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", 30000, null, "71d23c1b-8660-4c51-bd37-89bb88c03a58");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", 30000, null, "1cf7a2e1-81ed-4b41-bb67-63a69034a672");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("732e234d-eb57-4049-84d3-53cd124fb000")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("71d23c1b-8660-4c51-bd37-89bb88c03a58")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("71d23c1b-8660-4c51-bd37-89bb88c03a58")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("1cf7a2e1-81ed-4b41-bb67-63a69034a672")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("1cf7a2e1-81ed-4b41-bb67-63a69034a672")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
